import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Suspense } from "react";
import "./globals.css";
import { ConvexClientProvider } from "@/components/ConvexClientProvider";
import NavigationProvider from "@/components/navigation/navigation-provider";
import { PageSkeleton } from "@/components/skeletons";
import { ThemeProvider } from "@/components/theme-provider";
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
	icons: {
		icon: "/convex.svg",
	},
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<ThemeProvider
					attribute="class"
					defaultTheme="system"
					enableSystem
					disableTransitionOnChange
				>
					<Suspense fallback={<PageSkeleton />}>
						<ConvexClientProvider>
							{/* <ViewTransition> */}
							<NavigationProvider>
								<main className="h-[calc(100vh-6rem)] pt-24" id="main-content">
									{children}
								</main>
								<Toaster />
							</NavigationProvider>
							{/* </ViewTransition> */}
						</ConvexClientProvider>
					</Suspense>
				</ThemeProvider>
			</body>
		</html>
	);
}
