export const env = {
	NODE_ENV: process.env.NODE_ENV,
	WORKOS_API_KEY: process.env.WORKOS_API_KEY,
	WORKOS_WEBHOOK_SECRET: process.env.WORKOS_WEBHOOK_SECRET,
	WORKOS_CLIENT_ID: process.env.WORKOS_CLIENT_ID,
	LISTINGS_WEBHOOK_ALLOWED_ORIGIN:
		process.env.LISTINGS_WEBHOOK_ALLOWED_ORIGIN ?? "*",
	LISTINGS_WEBHOOK_API_KEY: process.env.LISTINGS_WEBHOOK_API_KEY,
	LAWYER_IDENTITY_PROVIDER:
		process.env.LAWYER_IDENTITY_PROVIDER ?? "mock_persona",
	OWNERSHIP_LEDGER_SOURCE: process.env.OWNERSHIP_LEDGER_SOURCE ?? "ledger",
	FORMANCE_CLIENT_ID: process.env.FORMANCE_CLIENT_ID,
	FORMANCE_CLIENT_SECRET: process.env.FORMANCE_CLIENT_SECRET,
	FORMANCE_SERVER_URL: process.env.FORMANCE_SERVER_URL,
} as const;

export const isTestEnv =
	env.NODE_ENV === "test" || typeof process.env.VITEST_WORKER_ID === "string";
